name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  dependabotnotifier:
    runs-on: ubuntu-latest
    if: false
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        name: Build and push Docker image
        with:
          team: appsec
          image_suffix: dependabot
          pull: true
          build_args: |
            APP=dependabotnotifier
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/dependabotnotifier.yaml
          IMAGE: ${{ steps.docker-build-push.outputs.IMAGE }}
  naisteamnotifier:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        name: Build and push Docker image
        with:
          team: appsec
          image_suffix: naisteam
          pull: true
          build_args: |
            APP=naisteamnotifier
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/naisteamnotifier.yaml
          IMAGE: ${{ steps.docker-build-push.outputs.IMAGE }}